// The workflows an adopted repository gets, rendered from the adoption record
// (#165). `scripts/init.mts` copies `templates/.github/workflows/**` verbatim
// and leaves the adopting repository to edit `AGENTIC_TEST_CMD` by hand, while
// the check names its ruleset requires are computed somewhere else entirely
// (`detectTestCheckName` in the same installer). Two answers to one question
// is one answer too many: the workflow and the ruleset could name different
// checks with nothing noticing.
//
// This module makes them one answer. `renderWorkflows(record, templates)`
// returns both the file contents and the list of check names those contents
// produce, so a caller that writes the files and a caller that sets the
// ruleset read the same list — it is computed once, and there is nothing for
// the two to disagree about.
//
// **Rendering is pure.** It takes a record and a map of template texts and
// returns strings. It reads no file, writes no file and asks nothing of the
// network; `readTemplates` is the one function here that touches the disk, and
// it only reads the templates this repository ships. `scripts/adopt.mts
// --workflows` is what writes anything.
//
// **What is rendered, and what is copied.** The templates carry no
// placeholders — they are working files this repository runs — so rendering
// anchors on lines that are already there rather than on markers invented for
// it. Only `agentic-checks.yml` is rendered: its commented `AGENTIC_TEST_CMD`
// line becomes the recorded test command, and a `test` and a `check` job are
// appended for the two recorded commands. `guard-main.yml` and
// `issue-lint.yml` name no command and run on `push`/`issues` rather than on a
// pull request, so they are copied verbatim under the marker and contribute no
// check name.
//
// **The marker is what protects a hand-written file.** Every file this module
// renders carries `generated by agentic-setup adopt` on its first lines
// (`MARKER`, `MARKER_LINES`). A file without it was written by a person, and
// `--workflows` skips it rather than overwriting it.
//
// **Crash policy: fail closed.** Every function either returns the answer or
// throws a named `WorkflowError`. A template that is not there, a template
// whose substitution anchor has been edited away, and a recorded command that
// cannot be rendered into YAML are each a named refusal — never a file emitted
// with the placeholder still in it, and never a workflow that cannot run.
// Only ENOENT reads as "the template is not there"; every other errno fails
// closed as `workflows:unreadable`.
//
// Node built-ins only; there is no YAML writer among them, so the rendering is
// textual and the two anchors below are checked before anything is replaced.
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { OWNED_WORKFLOWS } from './inventory.mts';
import type { AdoptionRecord } from './record.mts';

/** The marker a generated workflow carries, so the tool can recognise its own work. */
export const MARKER = 'generated by agentic-setup adopt';

/** How many of a file's first lines the marker may appear on. */
export const MARKER_LINES = 3;

/** Where the workflows live inside a repository, generated or not. */
export const WORKFLOW_DIR = join('.github', 'workflows');

/** The one workflow whose contents depend on the record; the other two do not. */
export const CHECKS_WORKFLOW = 'agentic-checks.yml';

/** The job the recorded test command becomes, and the check name it produces. */
export const TEST_JOB = 'test';

/** The job the recorded check command becomes, and the check name it produces. */
export const CHECK_JOB = 'check';

/**
 * The line `templates/.github/workflows/agentic-checks.yml` carries commented
 * out, and the anchor the recorded test command replaces. It is a real line of
 * a working file rather than a placeholder invented for this module, so a
 * template edit that removes it is a refusal (below) and not a silent no-op.
 */
const TEST_CMD_ANCHOR = /^([ \t]*)# AGENTIC_TEST_CMD: .*$/m;

/** The second anchor: the jobs mapping the generated jobs are appended to. */
const JOBS_ANCHOR = /^jobs:[ \t]*$/m;

/** Every named reason this module can refuse to render for. */
export type WorkflowReason =
  | 'workflows:template-missing'
  | 'workflows:template-unreadable'
  | 'workflows:template-anchor-missing'
  | 'workflows:jobs-not-last'
  | 'workflows:command-not-renderable';

/**
 * The one way out on a render this module refuses: a named `reason` a caller
 * can branch on, and the `field` it rejected — a template name or a record
 * field — when there is one. The message is for a person; the reason is the
 * contract.
 */
export class WorkflowError extends Error {
  readonly reason: WorkflowReason;
  readonly field: string | null;

  constructor(reason: WorkflowReason, message: string, field: string | null = null) {
    super(message);
    this.name = 'WorkflowError';
    this.reason = reason;
    this.field = field;
  }
}

/** One rendered file: its name, its contents, its jobs, and whether it was copied. */
export type RenderedWorkflow = {
  /** The file's name under `.github/workflows`. */
  name: string;
  /** The whole file, marker included, ready to be written. */
  content: string;
  /** The job ids of the rendered file, in file order. */
  jobs: string[];
  /** True when the body under the marker is the template, byte for byte. */
  verbatim: boolean;
};

/** A gap the rendering names, in the vocabulary `scripts/lib/adopt/inventory.mts` uses. */
export type WorkflowGap = 'test-command:none';

/** What `renderWorkflows` answers with. `checks` is the one list of check names. */
export type Rendering = {
  files: RenderedWorkflow[];
  /**
   * The status checks these files produce on a pull request: the job ids of
   * the rendered `agentic-checks.yml`, and nothing else. The other two
   * workflows run on `push` and on `issues`, so requiring them of a pull
   * request would block every merge on a check that never runs.
   */
  checks: string[];
  /** What the record could not answer, named rather than papered over. */
  gaps: WorkflowGap[];
};

/** Where this repository keeps the templates `scripts/init.mts` ships. */
export function templateDir(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  return join(here, '..', '..', '..', 'templates', '.github', 'workflows');
}

/**
 * The three shipped templates, by file name. The only function here that
 * reads the disk, and it reads nothing but this repository's own templates —
 * never anything in the repository being adopted.
 */
export function readTemplates(dir: string = templateDir()): Record<string, string> {
  const templates: Record<string, string> = {};
  for (const name of OWNED_WORKFLOWS) {
    try {
      templates[name] = readFileSync(join(dir, name), 'utf8');
    } catch (err) {
      const missing = (err as NodeJS.ErrnoException)?.code === 'ENOENT';
      throw new WorkflowError(
        missing ? 'workflows:template-missing' : 'workflows:template-unreadable',
        `${join(dir, name)} ${missing ? 'is not there' : `could not be read: ${(err as Error).message}`}`,
        name,
      );
    }
  }
  return templates;
}

/** True when the marker sits on the file's first lines — that is, when this tool wrote it. */
export function isGenerated(text: string): boolean {
  return text.split('\n').slice(0, MARKER_LINES).join('\n').includes(MARKER);
}

/** The header every generated file carries; exactly `MARKER_LINES` lines. */
const header = (): string =>
  [
    `# ${MARKER} — the commands come from \`agentic.config.json\`, not from this file.`,
    '# Regenerate it with `node scripts/adopt.mts --workflows`; edits made here are lost.',
    '# A workflow without this marker on its first lines is never overwritten.',
  ].join('\n');

/**
 * A command as a single-quoted YAML scalar. Quoting is not decoration: a
 * command holding a `:` or a `#` is valid and would otherwise change what the
 * YAML means. A command holding a newline or a control character cannot be
 * rendered on one line at all, and is refused rather than truncated.
 */
function yamlCommand(command: string, field: string): string {
  if (/[ -]/.test(command)) {
    throw new WorkflowError(
      'workflows:command-not-renderable',
      `${field} holds a newline or a control character and cannot be rendered into a workflow`,
      field,
    );
  }
  return `'${command.replace(/'/g, "''")}'`;
}

/**
 * The first top-level key after the `jobs:` line, or `null` when `jobs:` is
 * the last one. The generated jobs are appended at the end of the file, which
 * is inside the `jobs:` mapping only while nothing follows it: a template that
 * grew an `env:` or a second `on:` after `jobs:` would swallow them, and the
 * two checks the merge gate requires would silently not exist (#302). There is
 * no YAML parser among the built-ins to notice, so this is what notices.
 */
function keyAfterJobs(text: string): string | null {
  const lines = text.split('\n');
  const start = lines.findIndex((line) => JOBS_ANCHOR.test(line));
  if (start === -1) return null;
  for (const line of lines.slice(start + 1)) {
    if (line.trim() === '' || /^[ \t#]/.test(line)) continue;
    const key = line.match(/^([A-Za-z0-9_-]+):/);
    if (key) return key[1];
  }
  return null;
}

/**
 * The job ids of a workflow, in file order: every two-space key under the
 * `jobs:` line, up to the next top-level key. Blank lines inside the mapping
 * are part of it, which is why this walks lines rather than matching one
 * block — a single regex stops at the first empty line.
 */
function jobNames(text: string): string[] {
  const lines = text.split('\n');
  const start = lines.findIndex((line) => JOBS_ANCHOR.test(line));
  if (start === -1) return [];
  const names: string[] = [];
  for (const line of lines.slice(start + 1)) {
    if (line.trim() === '') continue;
    if (!/^[ \t]/.test(line)) break;
    const match = line.match(/^ {2}([A-Za-z0-9_-]+):[ \t]*$/);
    if (match) names.push(match[1]);
  }
  return names;
}

/**
 * One generated job. The toolchain block stays commented, as it is in the
 * template's `negative-control` job: the record says what the command is, and
 * it is the one thing about an adopted repository the record cannot answer.
 */
function jobFor(id: string, command: string, field: string): string {
  return [
    '',
    `  ${id}:`,
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v7',
    '      # --- toolchain setup: mirror your test workflow here -------------------',
    '      # - run: npm ci',
    '      # -----------------------------------------------------------------------',
    `      - name: ${id}`,
    `        run: ${yamlCommand(command, field)}`,
    '',
  ].join('\n');
}

/** The template for `name`, or a named refusal. */
function templateFor(templates: Record<string, string>, name: string): string {
  const text = templates[name];
  if (typeof text !== 'string' || text.length === 0) {
    throw new WorkflowError('workflows:template-missing', `the template for ${name} was not supplied`, name);
  }
  return text;
}

/** The rendered `agentic-checks.yml`: the two anchors, substituted. */
function renderChecks(record: AdoptionRecord, template: string): { content: string; gaps: WorkflowGap[] } {
  if (!TEST_CMD_ANCHOR.test(template)) {
    throw new WorkflowError(
      'workflows:template-anchor-missing',
      `${CHECKS_WORKFLOW} no longer carries the commented AGENTIC_TEST_CMD line this module substitutes into`,
      CHECKS_WORKFLOW,
    );
  }
  if (!JOBS_ANCHOR.test(template)) {
    throw new WorkflowError('workflows:template-anchor-missing', `${CHECKS_WORKFLOW} has no \`jobs:\` mapping to add a job to`, CHECKS_WORKFLOW);
  }
  const trailing = keyAfterJobs(template);
  if (trailing !== null) {
    throw new WorkflowError(
      'workflows:jobs-not-last',
      `${CHECKS_WORKFLOW} carries the top-level key \`${trailing}:\` after its \`jobs:\` mapping; the generated jobs are appended at the ` +
        'end of the file, so they would land under a key this module did not write and neither of the two checks would run. ' +
        'Move `jobs:` back to the end of the template, or teach this module to insert rather than append.',
      CHECKS_WORKFLOW,
    );
  }

  const gaps: WorkflowGap[] = [];
  const test = record.commands.test;
  const checkCommand = record.commands.check;

  // The test command first, so a template whose anchor holds a command that
  // cannot be rendered is refused before anything is appended.
  let body = template;
  if (test === null) {
    // The line stays commented: a workflow that exports an empty
    // AGENTIC_TEST_CMD is worse than one that exports none, because
    // `negative-control` would then run nothing and say so as if it had.
    gaps.push('test-command:none');
  } else {
    body = body.replace(TEST_CMD_ANCHOR, (_line, indent: string) => `${indent}AGENTIC_TEST_CMD: ${yamlCommand(test, 'commands.test')}`);
  }

  const ends = body.endsWith('\n') ? body : `${body}\n`;
  const jobs = [
    test === null ? '' : jobFor(TEST_JOB, test, 'commands.test'),
    checkCommand === null ? '' : jobFor(CHECK_JOB, checkCommand, 'commands.check'),
  ].join('');
  return { content: `${header()}\n\n${ends}${jobs}`, gaps };
}

/**
 * The three workflow files an adoption record implies, and the check names
 * they produce. Pure: a record and the template texts in, strings out.
 */
export function renderWorkflows(record: AdoptionRecord, templates: Record<string, string>): Rendering {
  const files: RenderedWorkflow[] = [];
  let gaps: WorkflowGap[] = [];
  let checks: string[] = [];

  for (const name of OWNED_WORKFLOWS) {
    const template = templateFor(templates, name);
    if (name !== CHECKS_WORKFLOW) {
      const content = `${header()}\n\n${template}`;
      files.push({ name, content, jobs: jobNames(content), verbatim: true });
      continue;
    }
    const rendered = renderChecks(record, template);
    const jobs = jobNames(rendered.content);
    files.push({ name, content: rendered.content, jobs, verbatim: false });
    // The one list: the ruleset's required checks and the workflow's jobs are
    // this same array, read out of the file that was just rendered.
    checks = jobs;
    gaps = rendered.gaps;
  }

  return { files, checks, gaps };
}
