#!/usr/bin/env node
// Cases for the generated workflows (#165): `scripts/lib/adopt/workflows.mts`
// renders the three workflow files from the templates plus the adoption
// record, and `scripts/adopt.mts --workflows` is the only thing that writes
// them into an adopted repository.
//
// Two kinds of case, deliberately:
//  - the **writes** are proved by spawning the real script (CLAUDE.md
//    invariant 6) against throwaway git repositories, with a small fake `gh`
//    first on PATH for the three reads `takeInventory` makes;
//  - the **rendering** is a pure function — it takes a record and returns
//    strings — and the acceptance criterion asks for the list of check names
//    it *returns*, which no amount of spawning can observe. So this one
//    module is imported, and the job names of the file it rendered are
//    re-parsed here, by a second implementation, and compared with that list.
//    That comparison is the whole point: the ruleset and the workflow are
//    computed once or they are not.
//
// The record's shape, the marker's text and the three workflow names are
// written out as literals below. They are the contract the script is held to,
// and importing them from the module that produces them would let both sides
// move together without a case noticing.
//
// Negative control: on the base `scripts/lib/adopt/workflows.mts` does not
// exist, so the import below answers `null` and every rendering case fails on
// its own assertion; `--workflows` is not a flag there either, so every spawn
// exits 1 on usage and no file is ever written. The substitution assertions
// fail for the reason the issue names: nothing on the base substitutes
// anything into a workflow — `scripts/init.mts` copies
// `templates/.github/workflows/**` verbatim.
import { spawnSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { check, cleanup, commit, finish, git, tempRepo, RUNTIME, ROOT } from './lib/harness.mts';

/** The three workflows this setup owns, as `docs/adopt.md` names them. */
const OWNED = ['agentic-checks.yml', 'guard-main.yml', 'issue-lint.yml'];

/** The marker a generated file carries, as the acceptance criterion words it. */
const MARKER = 'generated by agentic-setup adopt';

/** How many first lines of a file the marker may appear on. */
const MARKER_WINDOW = 3;

/** The record's name, at the adopted repository's root. */
const RECORD_FILE = 'agentic.config.json';

/** Where the workflows land inside the adopted repository. */
const WORKFLOWS = '.github/workflows';

// --- the module under test, imported rather than spawned --------------------
// Absent on the base: the import throws there and every case below fails on
// the assertion rather than crashing the file, so the red is a readable list
// of failures instead of one stack trace.
type Rendered = { name: string; content: string; jobs: string[]; verbatim: boolean };
type Rendering = { files: Rendered[]; checks: string[]; gaps: string[] };
type Module = {
  MARKER: string;
  MARKER_LINES: number;
  readTemplates: (dir?: string) => Record<string, string>;
  renderWorkflows: (record: unknown, templates: Record<string, string>) => Rendering;
  isGenerated: (text: string) => boolean;
};

let mod: Module | null = null;
try {
  mod = (await import('../scripts/lib/adopt/workflows.mts')) as unknown as Module;
} catch {
  mod = null;
}

check('scripts/lib/adopt/workflows.mts exists and exports renderWorkflows', typeof mod?.renderWorkflows === 'function');
check('it exports the template reader and the marker test', typeof mod?.readTemplates === 'function' && typeof mod?.isGenerated === 'function');
check('it exports the marker the generated files carry', mod?.MARKER === MARKER, String(mod?.MARKER));

// --- a fake `gh` -------------------------------------------------------------
const FAKE_GH = `#!/usr/bin/env bash
case "\${1:-} \${2:-}" in
  "api repos/{owner}/{repo}")
    echo '{"default_branch":"main","allow_auto_merge":true,"delete_branch_on_merge":false}'
    ;;
  "api repos/{owner}/{repo}/rules/branches/main")
    echo '[{"type":"pull_request","parameters":{"required_approving_review_count":1}},{"type":"required_status_checks","parameters":{"required_status_checks":[{"context":"scope"},{"context":"negative-control"}]}}]'
    ;;
  "label list")
    echo '[]'
    ;;
  *)
    echo "fake-gh: unknown command: $*" >&2
    exit 1
    ;;
esac
`;

const fakeGhDir = mkdtempSync(join(tmpdir(), 'agentic-fakegh-workflows-'));
cleanup(() => rmSync(fakeGhDir, { recursive: true, force: true }));
writeFileSync(join(fakeGhDir, 'gh'), FAKE_GH);
chmodSync(join(fakeGhDir, 'gh'), 0o755);
const PATH_WITH_FAKE_GH = `${fakeGhDir}:${process.env.PATH ?? ''}`;

// This repository dogfoods itself, so the shell running the suite may have the
// detection overrides set for real; every case below asserts the *detected*
// commands.
const { AGENTIC_TEST_CMD: _t, AGENTIC_CHECK_CMD: _c, ...BASE_ENV } = process.env;

function adopt(args: string[], cwd: string) {
  const r = spawnSync(RUNTIME, [join(ROOT, 'scripts', 'adopt.mts'), ...args], {
    cwd,
    encoding: 'utf8',
    env: { ...BASE_ENV, PATH: PATH_WITH_FAKE_GH },
  });
  return { status: r.status, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
}

function parse(stdout: string): any {
  try {
    return JSON.parse(stdout);
  } catch {
    return null;
  }
}

/** A committed throwaway repository; `files` land in the initial commit. */
function fixture(files: Record<string, string>): string {
  const dir = tempRepo();
  commit(dir, { 'README.md': '# fixture\n', ...files }, 'initial');
  return dir;
}

/** package.json with a `check` script and, optionally, a `test` one. */
const pkg = (withTest: boolean): string =>
  JSON.stringify({ name: 'fx', scripts: withTest ? { test: 'node t.mjs', check: 'tsc' } : { check: 'tsc' } });

/**
 * The job ids of a workflow, re-parsed here by a second implementation: the
 * text after the `jobs:` line, every two-space key under it. The module's own
 * parser walks lines; this one is a regex over the remainder, so the two
 * cannot drift together.
 */
function jobIds(text: string): string[] {
  const after = text.split(/^jobs:[ \t]*$/m)[1] ?? '';
  return [...after.matchAll(/^ {2}([A-Za-z0-9_-]+):[ \t]*$/gm)].map((m) => m[1]);
}

/** True when the marker sits within the file's first lines, as the refusal reads them. */
const marked = (text: string): boolean => text.split('\n').slice(0, MARKER_WINDOW).join('\n').includes(MARKER);

/** An adoption record as `scripts/lib/adopt/record.mts` writes one, as a literal. */
const recordOf = (test: string | null, checkCmd: string | null, checks: string[] = []): unknown => ({
  version: 1,
  stack: 'node',
  commands: { test, check: checkCmd },
  checks,
  hooks: [],
  proof: { dir: 'proof' },
  labels: { source: 'scripts/init.mts' },
  generatedAt: '2026-01-01T00:00:00.000Z',
  generatedBy: 'agentic-setup/adopt',
});

/** Calls the renderer, answering `null` when the module or the call is not there. */
function render(record: unknown, templates?: Record<string, string>): Rendering | null {
  if (!mod) return null;
  try {
    return mod.renderWorkflows(record, templates ?? mod.readTemplates());
  } catch {
    return null;
  }
}

/** The reason a refused render carries, or ''. */
function renderReason(record: unknown, templates: Record<string, string>): string {
  if (!mod) return '';
  try {
    mod.renderWorkflows(record, templates);
    return '';
  } catch (err) {
    return String((err as { reason?: unknown })?.reason ?? '');
  }
}

const fileNamed = (r: Rendering | null, name: string): Rendered | undefined => r?.files.find((f) => f.name === name);

// --- A: rendering is pure, and renders all three ----------------------------
/** The shipped templates, or `{}` when the module that reads them is not there. */
function shippedTemplates(): Record<string, string> {
  if (!mod) return {};
  try {
    return mod.readTemplates();
  } catch {
    return {};
  }
}

const templates = shippedTemplates();
check('readTemplates reads the three shipped templates', OWNED.every((name) => (templates[name] ?? '').length > 0), Object.keys(templates).join(', '));

const full = render(recordOf('npm test', 'npm run check', ['negative-control', 'scope']));
check('renderWorkflows returns the three workflow files', full?.files.map((f) => f.name).join(',') === OWNED.join(','), full?.files.map((f) => f.name).join(','));
check('every rendered file carries the marker on its first lines', (full?.files ?? []).length === 3 && (full?.files ?? []).every((f) => marked(f.content)), (full?.files ?? []).map((f) => f.content.split('\n')[0]).join(' | '));
check('the marker window the module documents is the one the cases read', mod?.MARKER_LINES === MARKER_WINDOW, String(mod?.MARKER_LINES));

const checksFile = fileNamed(full, 'agentic-checks.yml');
check(
  'the test command is substituted into the generated checks workflow',
  (checksFile?.content ?? '').includes("AGENTIC_TEST_CMD: 'npm test'"),
  checksFile?.content ?? '',
);
check(
  'the template placeholder the installer copies verbatim is gone',
  checksFile !== undefined && !checksFile.content.includes('# AGENTIC_TEST_CMD: npm test'),
  checksFile?.content ?? '',
);
check(
  'the check command is substituted into a job of its own',
  (checksFile?.content ?? '').includes("run: 'npm run check'"),
  checksFile?.content ?? '',
);
check('the generated checks workflow is not a verbatim copy', checksFile?.verbatim === false, String(checksFile?.verbatim));

for (const name of ['guard-main.yml', 'issue-lint.yml']) {
  const rendered = fileNamed(full, name);
  check(`${name} is still copied verbatim, under the marker`, rendered?.verbatim === true && rendered.content.endsWith(templates[name] ?? '\u0000'), name);
}

// --- B: one list of check names, for the workflow and for the ruleset -------
check(
  'the checks the renderer returns are exactly the job names of the file it rendered',
  full !== null && jobIds(checksFile?.content ?? '').join(',') === full.checks.join(','),
  `returned: ${full?.checks.join(',')} | in the file: ${jobIds(checksFile?.content ?? '').join(',')}`,
);
check(
  'the returned checks name the two loop checks and the two generated commands',
  ['scope', 'negative-control', 'test', 'check'].every((name) => (full?.checks ?? []).includes(name)),
  full?.checks.join(','),
);
check('the renderer reports the job names of the generated file, not of the others', fileNamed(full, 'guard-main.yml')?.jobs.join(',') === 'direct-push', fileNamed(full, 'guard-main.yml')?.jobs.join(','));
check('a record whose commands are both detected reports no gap', (full?.gaps ?? ['x']).length === 0, (full?.gaps ?? []).join(','));

// --- C: a record with no test command renders no test job -------------------
const noTest = render(recordOf(null, 'npm run check'));
const noTestFile = fileNamed(noTest, 'agentic-checks.yml');
check('a record with no test command reports test-command:none as a gap', (noTest?.gaps ?? []).includes('test-command:none'), (noTest?.gaps ?? []).join(','));
check('a record with no test command renders no test job', noTest !== null && !jobIds(noTestFile?.content ?? '').includes('test'), jobIds(noTestFile?.content ?? '').join(','));
check('a record with no test command leaves no test check in the returned list', noTest !== null && !noTest.checks.includes('test'), noTest?.checks.join(','));
check('a record with no test command still renders the check job', (noTest?.checks ?? []).includes('check'), noTest?.checks.join(','));
check(
  'a record with no test command never substitutes an empty command',
  noTest !== null && !/AGENTIC_TEST_CMD: ''/.test(noTestFile?.content ?? ''),
  noTestFile?.content ?? '',
);

// --- D: the renderer refuses rather than emitting a file that cannot run ----
check('a template that is not there is refused by name', renderReason(recordOf('npm test', 'tsc'), {}) === 'workflows:template-missing', renderReason(recordOf('npm test', 'tsc'), {}));

const anchorless: Record<string, string> = { ...templates, 'agentic-checks.yml': 'name: agentic-checks\n\njobs:\n  scope:\n    runs-on: ubuntu-latest\n' };
check(
  'a template whose substitution anchor is gone is refused, not emitted unsubstituted',
  renderReason(recordOf('npm test', 'tsc'), anchorless) === 'workflows:template-anchor-missing',
  renderReason(recordOf('npm test', 'tsc'), anchorless),
);
check(
  'a command that cannot be rendered into YAML is refused',
  renderReason(recordOf('npm test\nrm -rf /', 'tsc'), templates) === 'workflows:command-not-renderable',
  renderReason(recordOf('npm test\nrm -rf /', 'tsc'), templates),
);

// --- E: --workflows writes the files, from the record -----------------------
const repo = fixture({ 'package.json': pkg(true) });
check('the fixture starts with a record', adopt(['--record'], repo).status === 0, readFileSync(join(repo, RECORD_FILE), 'utf8'));

const e = adopt(['--workflows'], repo);
const eOut = parse(e.stdout);
check('--workflows exits 0', e.status === 0 && eOut !== null, `${e.stdout}\n${e.stderr}`);
check(
  '--workflows reports one outcome per workflow, all created',
  Array.isArray(eOut?.workflows) && eOut.workflows.length === 3 && eOut.workflows.every((w: any) => w?.outcome === 'created'),
  e.stdout,
);
check(
  '--workflows names each file it wrote, with the reason it wrote it',
  Array.isArray(eOut?.workflows) && OWNED.every((name) => eOut.workflows.some((w: any) => w?.file === `${WORKFLOWS}/${name}` && w?.reason === 'absent')),
  e.stdout,
);
check('--workflows put the three files under .github/workflows', OWNED.every((name) => existsSync(join(repo, WORKFLOWS, name))), WORKFLOWS);

const written = existsSync(join(repo, WORKFLOWS, 'agentic-checks.yml')) ? readFileSync(join(repo, WORKFLOWS, 'agentic-checks.yml'), 'utf8') : '';
check('the written workflow carries the record’s test command', written.includes("AGENTIC_TEST_CMD: 'npm test'"), written);
check('the written workflow carries the record’s check command', written.includes("run: 'npm run check'"), written);
check('the written workflow carries the marker that protects it', marked(written), written.split('\n').slice(0, MARKER_WINDOW).join('\n'));
check(
  'the checks the script printed are the job names of the file it wrote',
  Array.isArray(eOut?.checks) && eOut.checks.join(',') === jobIds(written).join(','),
  `printed: ${(eOut?.checks ?? []).join(',')} | in the file: ${jobIds(written).join(',')}`,
);
check(
  '--workflows names the generated checks the ruleset does not require yet',
  Array.isArray(eOut?.missingFromRuleset) && eOut.missingFromRuleset.includes('test') && !eOut.missingFromRuleset.includes('scope'),
  e.stdout,
);
check(
  '--workflows wrote the workflows and nothing else',
  git(['status', '--porcelain'], repo).split('\n').sort().join('\n') === ['?? .github/', `?? ${RECORD_FILE}`].join('\n'),
  git(['status', '--porcelain'], repo),
);

// --- F: a second run rewrites nothing ---------------------------------------
const f = adopt(['--workflows'], repo);
const fOut = parse(f.stdout);
check('a second --workflows exits 0', f.status === 0 && fOut !== null, `${f.stdout}\n${f.stderr}`);
check(
  'a second --workflows skips every file as unchanged',
  Array.isArray(fOut?.workflows) && fOut.workflows.every((w: any) => w?.outcome === 'skipped' && w?.reason === 'unchanged'),
  f.stdout,
);

// --- G: a record that moved is regenerated ----------------------------------
writeFileSync(join(repo, 'package.json'), JSON.stringify({ name: 'fx', scripts: { test: 'node t.mjs', check: 'tsc' }, workspaces: [] }));
writeFileSync(join(repo, 'Makefile'), 'test:\n\techo hi\n');
check('the moved fixture rewrites its record', adopt(['--record', '--force'], repo).status === 0, readFileSync(join(repo, RECORD_FILE), 'utf8'));
const g = adopt(['--workflows'], repo);
const gOut = parse(g.stdout);
const gChecks = existsSync(join(repo, WORKFLOWS, 'agentic-checks.yml')) ? readFileSync(join(repo, WORKFLOWS, 'agentic-checks.yml'), 'utf8') : '';
check('--workflows over a moved record exits 0', g.status === 0 && gOut !== null, `${g.stdout}\n${g.stderr}`);
check(
  '--workflows reports the generated file it rewrote as updated',
  Array.isArray(gOut?.workflows) && gOut.workflows.some((w: any) => w?.file === `${WORKFLOWS}/agentic-checks.yml` && w?.outcome === 'updated' && w?.reason === 'regenerated'),
  g.stdout,
);
check('the rewritten workflow carries the newly recorded command', gChecks.includes("AGENTIC_TEST_CMD: 'make test'"), gChecks);

// --- H: a hand-written workflow is skipped, never overwritten ---------------
const handWritten = '# my own checks, written by a person\nname: agentic-checks\non: [push]\njobs:\n  mine:\n    runs-on: ubuntu-latest\n';
const guarded = fixture({ 'package.json': pkg(true), '.github/workflows/agentic-checks.yml': handWritten });
check('the guarded fixture starts with a record', adopt(['--record'], guarded).status === 0, readFileSync(join(guarded, RECORD_FILE), 'utf8'));

const h = adopt(['--workflows'], guarded);
const hOut = parse(h.stdout);
check('--workflows over a hand-written workflow exits 0', h.status === 0 && hOut !== null, `${h.stdout}\n${h.stderr}`);
check(
  'a workflow without the marker is skipped, with the reason',
  Array.isArray(hOut?.workflows) &&
    hOut.workflows.some((w: any) => w?.file === `${WORKFLOWS}/agentic-checks.yml` && w?.outcome === 'skipped' && w?.reason === 'not-generated'),
  h.stdout,
);
check(
  'a hand-written workflow is left byte-identical',
  readFileSync(join(guarded, WORKFLOWS, 'agentic-checks.yml'), 'utf8') === handWritten,
  readFileSync(join(guarded, WORKFLOWS, 'agentic-checks.yml'), 'utf8'),
);
check(
  'the workflows it does own are still written beside it',
  ['guard-main.yml', 'issue-lint.yml'].every((name) => existsSync(join(guarded, WORKFLOWS, name))),
  WORKFLOWS,
);
check('isGenerated says a hand-written file is not ours', mod?.isGenerated(handWritten) === false, String(mod?.isGenerated(handWritten)));
check('isGenerated says a generated file is ours', mod?.isGenerated(written) === true, String(mod?.isGenerated(written)));

// --- I: no record is a refusal, not a guess ---------------------------------
const bare = fixture({ 'package.json': pkg(true) });
const before = git(['status', '--porcelain'], bare);
const i = adopt(['--workflows'], bare);
const iOut = parse(i.stdout);
check('--workflows without a record exits 1', i.status === 1 && iOut !== null, `${i.stdout}\n${i.stderr}`);
check('--workflows without a record refuses by name', iOut?.reason === 'workflows:no-record', i.stdout);
check('--workflows without a record writes nothing', git(['status', '--porcelain'], bare) === before, git(['status', '--porcelain'], bare));
check('--workflows without a record creates no workflows directory', !existsSync(join(bare, WORKFLOWS)), WORKFLOWS);

// --- J: usage ----------------------------------------------------------------
const jBoth = adopt(['--workflows', '--record'], repo);
check(
  '--workflows with a second mode flag is a usage error',
  jBoth.status === 1 && /usage/.test(parse(jBoth.stdout)?.error ?? ''),
  `${jBoth.stdout}\n${jBoth.stderr}`,
);
check(
  'the usage line names --workflows',
  /--workflows/.test(parse(jBoth.stdout)?.error ?? ''),
  `${jBoth.stdout}\n${jBoth.stderr}`,
);
const jForce = adopt(['--workflows', '--force'], repo);
check(
  '--force is not a modifier of --workflows: a hand-written file has no way past the refusal',
  jForce.status === 1 && /usage/.test(parse(jForce.stdout)?.error ?? ''),
  `${jForce.stdout}\n${jForce.stderr}`,
);

// --- K: rendering writes nothing --------------------------------------------
const untouched = fixture({ 'package.json': pkg(true) });
mkdirSync(join(untouched, WORKFLOWS), { recursive: true });
const beforeRender = git(['status', '--porcelain'], untouched);
render(recordOf('npm test', 'npm run check'));
check('renderWorkflows writes nothing of its own', git(['status', '--porcelain'], untouched) === beforeRender, git(['status', '--porcelain'], untouched));
check('renderWorkflows leaves the shipped templates as it found them', OWNED.every((name) => readFileSync(join(ROOT, 'templates', '.github', 'workflows', name), 'utf8') === templates[name]), 'templates changed');

// --- L: the documentation the acceptance criterion asks for -----------------
const docs = readFileSync(join(ROOT, 'docs', 'adopt.md'), 'utf8');
check('docs/adopt.md documents the --workflows flag', /node scripts\/adopt\.mts --workflows/.test(docs));
check('docs/adopt.md documents the marker that protects a hand-written file', docs.includes(MARKER));
check('docs/adopt.md says which templates are still copied verbatim', /verbatim/.test(docs) && /guard-main\.yml/.test(docs) && /issue-lint\.yml/.test(docs));

// --- M: the generated jobs are never appended after a key we did not write ---
// `renderChecks` adds its jobs at the end of the file. That is only the `jobs:`
// mapping while `jobs:` is the last top-level key of the template; a key after
// it would swallow them, and the workflow would run neither — silently, since
// there is no YAML parser among the built-ins to notice (#302).
const withTrailingKey = { ...templates, 'agentic-checks.yml': `${templates['agentic-checks.yml'] ?? ''}\nenv:\n  SOMETHING: 1\n` };
check(
  'a template carrying a top-level key after jobs: is refused by name',
  renderReason(recordOf('npm test', 'npm run check'), withTrailingKey) === 'workflows:jobs-not-last',
  renderReason(recordOf('npm test', 'npm run check'), withTrailingKey) || '(rendered without refusing)',
);
check(
  'nothing is rendered past a key the module did not write',
  render(recordOf('npm test', 'npm run check'), withTrailingKey) === null,
  'rendered anyway',
);
check('docs/adopt.md names that refusal', docs.includes('workflows:jobs-not-last'), 'jobs-not-last');

finish();
