#!/usr/bin/env node
// adopt — reports what a repository has, and asks before writing anything
// (#162). `scripts/init.mts` writes first and reports afterwards, which is
// the wrong order for a repository that is not yours; this script reverses
// it. Run from inside the repository being looked at.
//
//   node scripts/adopt.mts --inventory [--run-proof]
//   node scripts/adopt.mts --plan-issue
//   node scripts/adopt.mts --record [--force]
//   node scripts/adopt.mts --workflows
//   node scripts/adopt.mts --hooks
//   node scripts/adopt.mts --pr
//
// `--inventory` prints the report of `scripts/lib/adopt/inventory.mts` as
// JSON on stdout and performs **no write of any kind** — without `--run-proof`
// below, which hands the tree to the repository's own test command, and that
// command may write, move or remove any file or directory it likes: no file is
// created or touched, and the only `gh` calls are reads (`api
// repos/{owner}/{repo}`, the default branch's effective rules, `label list`).
// It reads one more thing from disk than the inventory does — the record.
//
// It answers two things the read-back was silent about (#459, absorbing #460):
// `proof`, whether the command this repository would prove itself with *passes*
// here and not only that one resolved — run **only** under `--run-proof`, a
// modifier of `--inventory` as `--force` is of `--record`, and the gap
// `proof:red` joins `gaps` only when a run happened and did not pass, a gap
// being a fact about the repository where "nobody looked" is one about the run;
// and `labelNeighbours`, each label the dictionary wants that is absent while a
// near neighbour is already there (a bare `human` where it wants
// `human:pending`), with `labelNeighbourRule` stating what the three rules do
// not reach — reporting being the whole of it, since that choice is the
// adopter's. `scripts/doctor.mts` asks both under the same flag and answers the
// same way, and its header has the reasoning; `docs/adopt.md` the rest.
//
// `--plan-issue` is the first mutation, and it is a question rather than a
// change: it opens a single `human:pending` issue whose body renders the
// inventory and lists, as checkboxes, exactly the gaps found and what adoption
// would do about each. It creates **both** labels of that question first — the
// one the issue carries, and the `human:decided` its own last line asks the
// reader for, which `--pr` refuses without (#366): on a repository nobody
// prepared, which is the only kind this script exists for, answering the plan
// used to mean creating a label by hand first. So a run writes at most two
// labels besides the issue, and exactly the ones the inventory read did not
// see. A second run opens no second issue, and a repository whose report names
// no gap gets none at all — before any `gh` call beyond the inventory's reads.
// Each refusal is named, with the three readers that honour the label, in the
// `--plan-issue` section of `docs/adopt.md`.
//
// `--record` is the second mutation, and it writes exactly one file:
// `agentic.config.json` at the repository root, the adoption record of
// `docs/decisions.md` item 15, built from the inventory by
// `scripts/lib/adopt/record.mts` — the one writer. It refuses to overwrite a
// record whose `generatedBy` is not this tool (`record:not-ours`), `--force` is
// the way past that, and either way a rewrite reports every field that changed.
//
// **Detection stays the default.** The record is compared with what
// `ci/lib/detect.mts` says on *every* run, not only when it is written, and
// `--inventory` reports each field where the two disagree as the gap
// `record:stale`. That comparison lives here rather than in
// `inventory.mts` because the inventory is what a repository *has*, read
// once; the record is a layer over it, and the values to compare against —
// `stack`, `test`, `check` — are already in the report, so no second
// detection run happens.
//
// `--workflows` is the third mutation, and it writes only under the adopted
// repository's `.github/workflows/`: the three files
// `scripts/lib/adopt/workflows.mts` renders from the record (#165), which also
// returns the list of check names those files produce — one list for the
// workflow and for the ruleset, so the two cannot name different checks. The
// record is the input and is required (`workflows:no-record`). A file that does
// not carry the `generated by agentic-setup adopt` marker was written by a
// person and is `skipped` with no `--force` past it; one that is already what
// would be written is `skipped` too. The `--workflows` section of
// `docs/adopt.md` names every outcome and every refusal.
//
// `--hooks` is the fourth mutation, and it writes exactly two things: the
// `pre-push` hook into the directory git says it runs hooks from, and the deny
// list into `.claude/settings.json`. What it installs is what the record's
// `hooks[]` names (#166), resolved by `scripts/lib/adopt/hooks.mts`, which
// plans without writing; a record is required (`hooks:no-record`). A hook a
// person wrote is never replaced, a name this setup does not ship installs
// nothing at all, the deny merge keeps every rule it did not seed, and a write
// that fails partway puts back everything already written — the install is
// whole or it is nothing. Running it twice is a no-op. Every outcome, reason
// and named error of the flag is the `--hooks` section of `docs/adopt.md`.
//
// `--pr` is the last step and the only one that touches the remote: it
// assembles the branch `chore/adopt-agentic-setup` out of the record, the
// generated workflows, the deny list and one deliberate red test, pushes it and
// opens a pull request (#167). It **refuses unless the plan issue
// `--plan-issue` opened carries `human:decided`**, and the ticked boxes of that
// issue are what it acts on (#368) — adoption is not something a script decides
// for a repository. Its body is `scripts/lib/adopt/pr-run.mts`, whose header
// states every refusal and what each one leaves behind, and `docs/adopt-pr.md`
// documents the whole flag: the decision it reads, the branch it assembles in
// the object database against a temporary index, the create-only push, the
// `{ held }` exit 2 over a branch that already exists, and the two generated
// checks that are expected red on that one pull request. `--force` is not a
// modifier of it. `adopt` never merges anything — `scripts/land.mts` does.
//
// **Crash policy: fail closed.** Any `git` or `gh` read that cannot answer
// prints `{ error: <named reason> }` and exits 1. No field is ever reported
// as absent because the read for it failed — "there is no ruleset" and "the
// ruleset could not be read" are different answers, and a caller acting on
// the first when the second is true would delete a protection it never saw.
// The record is held to the same rule on every flag, `--inventory`
// included: a record that is not the shape prints `{ error, field }` and
// exits 1 rather than being ignored, because a rejected record silently read
// as "no record" is a stale configuration nothing would ever report. A usage
// problem is reported the same way, before any call is made.
//
// Node built-ins only.
import { spawnSync } from 'node:child_process';
import { parseArgs } from '../ci/lib/args.mts';
import {
  LABEL_LIST_LIMIT,
  OWNED_WORKFLOWS,
  SEEDED_LABELS,
  isFailure,
  takeInventory,
  type CommandResult,
  type Gap,
  type Inventory,
} from './lib/adopt/inventory.mts';
import {
  GENERATED_BY,
  RECORD_FILE,
  RecordError,
  buildRecord,
  diffRecords,
  readRecord,
  staleFields,
  writeRecord,
  type AdoptionRecord,
} from './lib/adopt/record.mts';
import { chmodSync, closeSync, mkdirSync, mkdtempSync, openSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import {
  WORKFLOW_DIR,
  WorkflowError,
  isGenerated,
  readTemplates,
  renderWorkflows,
} from './lib/adopt/workflows.mts';
import { HookError, planHooks } from './lib/adopt/hooks.mts';
import { SLUG_PATTERN } from './lib/proof.mts';
import { fileURLToPath } from 'node:url';
import { ADOPTION_GLOBS } from './lib/adopt/pr.mts';
import { runPullRequest } from './lib/adopt/pr-run.mts';
import { gitIn } from './lib/adopt/git.mts';
import { unlinkSync } from 'node:fs';

const USAGE =
  'usage: node scripts/adopt.mts --inventory [--run-proof] | --plan-issue | --record [--force] | --workflows | --hooks | --pr';

/** The runner `--run-proof` spawns, beside this file; see `scripts/doctor.mts`. */
const PROOF_RUNNER = resolve(dirname(fileURLToPath(import.meta.url)), 'proof.mts');

/** A branch of the loop's shape, whose slug is what a proof is declared for. */
const BRANCH_SHAPE = /^[a-z]+\/\d+-([a-z0-9-]+)$/;

/** A label the dictionary wants, beside one this repository already carries. */
type Neighbour = { wanted: string; present: string; rule: 'case' | 'namespace' | 'tail' };

/**
 * What the three neighbour rules compare, printed whether they matched or not: a
 * detector implying a completeness it has not got is worse than a narrow one
 * that states its bound. `scripts/doctor.mts` applies the same three.
 */
const NEIGHBOUR_RULE =
  'a present label that differs from the wanted one only in case, or that is exactly its namespace (`human` for `human:pending`), or that is exactly its last segment (`bug` for `type:bug`); nothing else — what is left out is a different word for the same thing, `type:fix` where the dictionary wants `type:bug` or `documentation` where it wants `type:docs`, which needs a thesaurus rather than a rule';

/** The title the plan issue is deduplicated by; one per repository. */
const PLAN_ISSUE_TITLE = 'Adoption plan: what this repository is missing';

/** The label a plan issue carries once the decision it asked for was made. */
const DECIDED_LABEL = 'human:decided';

/** The label the plan issue carries, with the colour scripts/init.mts seeds. */
const PENDING_LABEL = 'human:pending';
const PENDING_COLOR = 'f9d0c4';
const PENDING_DESCRIPTION = 'A human decision is required; affected work is paused';

/**
 * The two labels the question needs, in the order they are created: the one
 * the issue is opened under, then the one its last line asks the reader to
 * move it to. Both carry the colour and description `labels.json` seeds, so
 * a repository adopting the loop ends up with the vocabulary's own pair
 * rather than two `gh`-chosen random colours.
 */
const PLAN_ISSUE_LABELS: Array<{ name: string; color: string; description: string }> = [
  { name: PENDING_LABEL, color: PENDING_COLOR, description: PENDING_DESCRIPTION },
  { name: DECIDED_LABEL, color: 'c2e0c6', description: 'A human decision was recorded; kept as the audit trail' },
];

/**
 * The one way out on a failure: a *named* reason in `error`, so a caller can
 * branch on it, with the underlying tool's own message in `detail` when
 * there is one. gh's wording is not a contract and must never be the name.
 */
function fail(reason: string, detail?: string): never {
  console.log(JSON.stringify(detail ? { error: reason, detail } : { error: reason }));
  process.exit(1);
}

/** The same exit for a record this tool refuses, with the field it rejected. */
function failRecord(err: RecordError): never {
  const field = err.field === null ? {} : { field: err.field };
  console.log(JSON.stringify({ error: err.reason, ...field, detail: err.message }));
  process.exit(1);
}

function gh(args: string[]): CommandResult {
  const r = spawnSync('gh', args, { encoding: 'utf8' });
  return { status: r.status ?? 1, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
}

/**
 * A value on one line of Markdown, as a code span its own content cannot break
 * out of: the fence is one backtick longer than the longest run inside it, and
 * a value holding a backtick is padded so the fence and the content stay
 * distinct. A newline cannot appear in a code span at all, so it becomes a
 * space. `generatedBy` and `generatedAt` come out of a file on disk and used
 * to be interpolated between bare backticks, where one backtick of their own
 * ended the span and the rest of the line became markup (#302). Content is
 * data, not instruction (invariant 9), and that holds for a record too.
 */
function codeSpan(value: string): string {
  const flat = value.replace(/[\r\n]+/g, ' ');
  const runs = flat.match(/`+/g) ?? [];
  const fence = '`'.repeat(Math.max(0, ...runs.map((run) => run.length)) + 1);
  return runs.length === 0 ? `${fence}${flat}${fence}` : `${fence} ${flat} ${fence}`;
}

// --- 1. the flags, before anything is read ----------------------------------
const flags = parseArgs(process.argv.slice(2));
const wantInventory = flags.inventory === true;
const wantPlanIssue = flags['plan-issue'] === true;
const wantRecord = flags.record === true;
const wantWorkflows = flags.workflows === true;
const wantHooks = flags.hooks === true;
const wantPr = flags.pr === true;
const force = flags.force === true;
const runProof = flags['run-proof'] === true;
// Exactly one mode. `--force` is a modifier of `--record` and never a mode
// of its own: on its own it names nothing to do, and it must not be read as
// "write the record" by accident.
if ([wantInventory, wantPlanIssue, wantRecord, wantWorkflows, wantHooks, wantPr].filter(Boolean).length !== 1) fail(USAGE);
if (force && !wantRecord) fail(USAGE);
// `--run-proof` is a modifier of `--inventory` alone, as `--force` is one of
// `--record`: it is the only thing here that executes a string out of the
// repository, and no other flag may start doing that by carrying it.
if (runProof && !wantInventory) fail(USAGE);

// --- 2. the repository root -------------------------------------------------
const top = spawnSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' });
if (top.status !== 0 || !(top.stdout ?? '').trim()) fail('root:not-a-git-repository');
const root = top.stdout.trim();

// --- 3. the report ----------------------------------------------------------
const inventory = takeInventory(root, gh, gitIn(root));
if (isFailure(inventory)) fail(inventory.error);

// --- 4. the adoption record, read on every run ------------------------------
// Read before anything is written, and validated before it is believed. A
// record that is not the shape stops the run here, whichever flag asked.
let existing: AdoptionRecord | null;
try {
  existing = readRecord(root);
} catch (err) {
  if (err instanceof RecordError) failRecord(err);
  throw err;
}

/** What the report says about the record: never the record itself, which detection replaces. */
type RecordView = { generatedBy: string; generatedAt: string; stale: string[] } | null;
/** `labelNeighbours` is empty when no absent label has one; the rule is always stated. */
type Report = Omit<Inventory, 'gaps'> & { gaps: Gap[]; record: RecordView; labelNeighbours: Neighbour[]; labelNeighbourRule: string };

const stale = existing === null ? [] : staleFields(existing, inventory);
const record: RecordView =
  existing === null ? null : { generatedBy: existing.generatedBy, generatedAt: existing.generatedAt, stale };
const report: Report = {
  ...inventory,
  gaps: stale.length > 0 ? [...inventory.gaps, 'record:stale'] : inventory.gaps,
  record,
  // `NEIGHBOUR_RULE`'s three rules over the labels the dictionary wanted and did
  // not find: the whole name, its namespace, its last segment, in that order.
  labelNeighbours: SEEDED_LABELS.filter((name) => !inventory.labels.includes(name)).flatMap((wanted) => {
    const lower = wanted.toLowerCase();
    const forms = [lower, lower.split(':')[0] ?? lower, lower.slice(lower.lastIndexOf(':') + 1)];
    return inventory.labels.flatMap((present): Neighbour[] => {
      const at = forms.indexOf(present.toLowerCase());
      const rule = at < 0 || (at === 0 && present === wanted) ? undefined : (['case', 'namespace', 'tail'] as const)[at];
      return rule === undefined ? [] : [{ wanted, present, rule }];
    });
  }),
  labelNeighbourRule: NEIGHBOUR_RULE,
};

/**
 * Whether the command this repository would prove itself with passes here:
 * `scripts/proof.mts`'s own report, spawned rather than reimplemented, so the
 * verdict is the one an adopter gets by hand and the run's bounds stay in the
 * file that owns them. The slug comes off HEAD as `scripts/doctor.mts` derives
 * it, so the two resolve one command; `tail` is dropped, and the report is
 * collected through a temporary file of this process rather than a pipe, which
 * a runner that prints and exits in one breath truncates — the same helper in
 * `scripts/doctor.mts` carries that measurement, and the directory is removed
 * on every path out of this one.
 */
function runTheProof(): Record<string, unknown> {
  const head = gitIn(root)(['rev-parse', '--abbrev-ref', 'HEAD']).stdout.trim();
  const slug = BRANCH_SHAPE.exec(head)?.[1] ?? (SLUG_PATTERN.test(head) ? head : 'no-branch');
  const dir = mkdtempSync(join(tmpdir(), 'agentic-adopt-proof-'));
  const report = join(dir, 'report.json');
  const fd = openSync(report, 'w');
  let text = '';
  try {
    spawnSync(process.execPath, [PROOF_RUNNER, slug], { cwd: root, stdio: ['ignore', fd, 'ignore'] });
    text = readFileSync(report, 'utf8');
  } catch {
    text = '';
  } finally {
    closeSync(fd);
    rmSync(dir, { recursive: true, force: true });
  }
  let printed: Record<string, unknown>;
  try {
    printed = JSON.parse(text.trim().split('\n').filter(Boolean).pop() ?? '') as Record<string, unknown>;
  } catch {
    printed = {};
  }
  // A runner that printed no outcome is a read that failed, and this file's
  // crash policy answers it: `{ error }`, exit 1. It is never the gap
  // `proof:red`, which says this repository's suite is red — a crashed runner is
  // no fact about the repository — and `scripts/doctor.mts` reports the same case
  // as `read-failed:proof`, so the two cannot disagree about it.
  if (typeof printed.outcome !== 'string') fail('read-failed:proof');
  const { tail: _tail, ...rest } = printed;
  return { ...rest, run: true };
}

if (wantInventory) {
  // Appended here rather than carried in `Report`, because a verdict only a run
  // can establish has no place in the report `--plan-issue` renders boxes from:
  // a box nobody can tick is worse than no box. A repository with no command at
  // all is `test-command:none` already, and is not named twice.
  const proof = runProof ? runTheProof() : { run: false, outcome: 'unrun' };
  const red = proof.run === true && proof.outcome !== 'pass' && proof.reason !== 'proof:no-command';
  console.log(JSON.stringify({ ...report, gaps: red ? [...report.gaps, 'proof:red'] : report.gaps, proof }));
  process.exit(0);
}

// --- 4b. --workflows: the files the record generates -------------------------
// Placed here, between the report and `--record`, because it is a reader of
// the record rather than a producer of one: the record is its only input, and
// a repository without one is refused rather than detected a second time.
// Everything it writes goes under `<root>/.github/workflows/`; nothing else on
// disk is touched, and the marker is what keeps a hand-written file safe.
if (wantWorkflows) {
  if (existing === null) {
    console.log(
      JSON.stringify({
        refused:
          `there is no ${RECORD_FILE} to generate from; run \`node scripts/adopt.mts --record\` first. ` +
          'The workflows are rendered from the record, so that the checks they produce and the checks the ' +
          'ruleset requires are one list rather than two.',
        reason: 'workflows:no-record',
      }),
    );
    process.exit(1);
  }

  /** The same exit as `failRecord`, for a render this tool refuses. */
  const failWorkflow = (err: WorkflowError): never => {
    const field = err.field === null ? {} : { field: err.field };
    console.log(JSON.stringify({ error: err.reason, ...field, detail: err.message }));
    process.exit(1);
  };

  let rendering;
  try {
    rendering = renderWorkflows(existing, readTemplates());
  } catch (err) {
    if (err instanceof WorkflowError) failWorkflow(err);
    throw err;
  }

  /** What happened to one file, and why. `skipped` always carries its reason. */
  type Outcome = { file: string; outcome: 'created' | 'updated' | 'skipped'; reason: string; jobs: string[] };
  const outcomes: Outcome[] = [];

  for (const rendered of rendering.files) {
    const shown = `${WORKFLOW_DIR}/${rendered.name}`;
    const path = join(root, WORKFLOW_DIR, rendered.name);
    // Only ENOENT is "there is no such file"; every other errno fails closed,
    // because writing over a file that could not be read is exactly what the
    // marker exists to prevent.
    let current: string | null;
    try {
      current = readFileSync(path, 'utf8');
    } catch (err) {
      if ((err as NodeJS.ErrnoException)?.code !== 'ENOENT') fail('workflows:unreadable', (err as Error).message);
      current = null;
    }

    if (current !== null && !isGenerated(current)) {
      outcomes.push({ file: shown, outcome: 'skipped', reason: 'not-generated', jobs: rendered.jobs });
      continue;
    }
    if (current === rendered.content) {
      outcomes.push({ file: shown, outcome: 'skipped', reason: 'unchanged', jobs: rendered.jobs });
      continue;
    }
    try {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, rendered.content);
    } catch (err) {
      fail('workflows:not-written', (err as Error).message);
    }
    outcomes.push({
      file: shown,
      outcome: current === null ? 'created' : 'updated',
      reason: current === null ? 'absent' : 'regenerated',
      jobs: rendered.jobs,
    });
  }

  // `checks` is the list the renderer returned — the job names of the file it
  // rendered, not a second computation over what was written. `record.checks`
  // is what the default branch's ruleset requires today, as the inventory read
  // it, so the difference is the work the ruleset still needs.
  console.log(
    JSON.stringify({
      workflows: outcomes,
      checks: rendering.checks,
      missingFromRuleset: rendering.checks.filter((name) => !existing.checks.includes(name)),
      gaps: rendering.gaps,
    }),
  );
  process.exit(0);
}

// --- 4c. --hooks: the hooks the record names ---------------------------------
// A reader of the record, like `--workflows`: the record is its only input,
// and a repository without one is refused rather than detected a second time.
// Everything it writes is a file the plan names — the `pre-push` hook under
// the directory git runs hooks from, and `.claude/settings.json` — and the
// marker is what keeps a hand-written hook safe.
if (wantHooks) {
  if (existing === null) {
    console.log(
      JSON.stringify({
        refused:
          `there is no ${RECORD_FILE} to install from; run \`node scripts/adopt.mts --record\` first. ` +
          'The hooks are installed from the record, so that what a repository has and what its record says are ' +
          'one answer rather than two.',
        reason: 'hooks:no-record',
      }),
    );
    process.exit(1);
  }

  /** The same exit as `failRecord`, for a plan this tool refuses. */
  const failHook = (err: HookError): never => {
    const field = err.field === null ? {} : { field: err.field };
    console.log(JSON.stringify({ error: err.reason, ...field, detail: err.message }));
    process.exit(1);
  };

  // Where git runs hooks from is git's answer and never a guess:
  // `core.hooksPath` moves it, and in a worktree `.git` is a file whose hooks
  // live in the common directory. `scripts/lib/adopt/inventory.mts` asks the
  // same question for its own report; this asks it again rather than planning
  // against an assumed `.git/hooks`.
  const hooksPath = gitIn(root)(['rev-parse', '--git-path', 'hooks']);
  if (hooksPath.status !== 0 || hooksPath.stdout.trim().length === 0) fail('hooks:unreadable');
  const hooksDir = resolve(root, hooksPath.stdout.trim());

  let plan;
  try {
    plan = planHooks(existing, { root, hooksDir });
  } catch (err) {
    if (err instanceof HookError) failHook(err);
    throw err;
  }

  /** What happened to one file, and why. Every outcome carries its reason. */
  type HookOutcome = {
    hook: string;
    file: string;
    outcome: 'created' | 'updated' | 'skipped';
    reason: string;
    deny?: unknown;
  };
  const OUTCOME = { create: 'created', update: 'updated', skip: 'skipped' } as const;
  const outcomes: HookOutcome[] = [];

  // What has been written so far, so a write that fails can be undone. The
  // header promises a fail-closed install and never a partial one, and the
  // plan is executed file by file: the `pre-push` hook landed before the
  // permission file was even attempted, so a settings write that failed used
  // to leave a repository half-installed and say only `hooks:not-written`
  // (#302). Each entry is put back as it was — deleted when it was absent,
  // restored byte for byte when it was not — before the refusal is printed.
  const done: Array<{ path: string; previous: string | null }> = [];
  const rollBack = (): void => {
    for (const entry of [...done].reverse()) {
      try {
        if (entry.previous === null) unlinkSync(entry.path);
        else writeFileSync(entry.path, entry.previous);
      } catch {
        // Nothing left to do about it: the refusal below is what is reported,
        // and a failure to undo must not replace the failure that caused it.
      }
    }
  };

  for (const entry of plan.entries) {
    const deny = entry.deny === null ? {} : { deny: entry.deny };
    if (entry.action !== 'skip' && entry.content !== null) {
      const path = join(root, entry.path);
      try {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, entry.content);
        done.push({ path, previous: entry.previous });
        if (entry.mode !== null) chmodSync(path, entry.mode);
      } catch (err) {
        rollBack();
        fail('hooks:not-written', (err as Error).message);
      }
    }
    outcomes.push({ hook: entry.hook, file: entry.path, outcome: OUTCOME[entry.action], reason: entry.reason, ...deny });
  }

  // `recorded` is what the record asked for, printed beside what happened to
  // it: a hook named there and `skipped` here is the one line that says the
  // repository does not have what its record claims.
  console.log(JSON.stringify({ hooks: outcomes, recorded: existing.hooks }));
  process.exit(0);
}

// --- 4d. --pr: the branch that proves itself ---------------------------------
// The last step, and the only one that touches the remote. It is a reader of
// the record like `--workflows` and `--hooks`, except that it will generate
// one when there is none: the sequence a person runs is `--inventory`,
// `--plan-issue`, the decision, `--pr`, and asking them for `--record` in
// between would be a step nothing verified. Nothing is written into the
// working tree at any point — the branch is assembled in the object database
// against a temporary index, which `scripts/lib/adopt/pr-run.mts` removes on
// every path out of it. That module is the whole of the flag except this
// printing (#302): the CLI supplies what it already read and turns the outcome
// into JSON and an exit code.
if (wantPr) {
  const outcome = runPullRequest({
    root,
    inventory,
    existing,
    gh,
    git: gitIn(root),
    planIssueTitle: PLAN_ISSUE_TITLE,
    decidedLabel: DECIDED_LABEL,
  });
  if (outcome.kind === 'error') {
    console.log(
      JSON.stringify({
        error: outcome.reason,
        ...(outcome.field === undefined || outcome.field === null ? {} : { field: outcome.field }),
        ...(outcome.detail === undefined ? {} : { detail: outcome.detail }),
      }),
    );
    process.exit(1);
  }
  console.log(JSON.stringify(outcome.body));
  // A branch someone else already holds is exit 2, the code `scripts/claim.mts`
  // uses for the same answer; a refusal a person answers is exit 1.
  process.exit(outcome.kind === 'ok' ? 0 : outcome.kind === 'held' ? 2 : 1);
}

// --- 5. --record: the one file adoption generates ---------------------------
if (wantRecord) {
  if (existing !== null && existing.generatedBy !== GENERATED_BY && !force) {
    console.log(
      JSON.stringify({
        refused:
          `${RECORD_FILE} says it was generated by \`${existing.generatedBy}\`, not by this tool; ` +
          'no person edits this file. Run `--record --force` to regenerate it, losing every hand edit.',
        reason: 'record:not-ours',
        generatedBy: existing.generatedBy,
      }),
    );
    process.exit(1);
  }
  const next = buildRecord(inventory);
  const changed = existing === null ? [] : diffRecords(existing, next);
  try {
    writeRecord(root, next);
  } catch (err) {
    fail('record:not-written', (err as Error).message);
  }
  console.log(JSON.stringify({ record: RECORD_FILE, written: true, changed }));
  process.exit(0);
}

// --- 6. --plan-issue: a repository with nothing to plan is not asked --------
// The plan issue is a question ("should adoption do these things?"), and a
// repository whose report names no gap has none to answer: the issue would
// carry an empty checklist, and a person would have to open it to find that
// out. `report.gaps`, not `inventory.gaps` — a stale record is worth
// planning even when the repository itself is whole. Refused here, before
// the open-issue search and before the label, so this run makes no `gh`
// call at all beyond the reads the inventory already did.
if (report.gaps.length === 0) {
  console.log(
    JSON.stringify({
      refused:
        'this repository already has everything the loop reads; there is nothing to plan, and an issue with an ' +
        'empty checklist asks nothing. Run `--inventory` to see the report it was decided from.',
      reason: 'plan-issue:nothing-to-plan',
      gaps: [],
    }),
  );
  process.exit(1);
}

// --- 7. --plan-issue: render the plan ---------------------------------------
const show = (value: string | null): string => (value === null ? 'none' : `\`${value}\``);

/** What adoption would do about each gap, in the gap's own words. */
const REMEDIES: Record<Gap, (report: Report) => string> = {
  'ruleset:absent': (r) =>
    `create the \`agentic-setup\` branch ruleset on \`${r.defaultBranch}\` (\`node scripts/init.mts --rules\`), ` +
    'requiring a pull request and the checks the merge gate reads',
  'ruleset:review-not-required': () =>
    "raise the ruleset's `required_approving_review_count` to 1, so an approval is what merges a pull request " +
    'rather than a label anyone can apply',
  // The two labels of the question are created by this very run, before the
  // issue is opened, so by the time anyone reads the checklist they exist:
  // counting them among the labels adoption *would* create would ask for work
  // already done (#366). The gap itself is unchanged — `inventory.mts`
  // computes it from a read taken before the write, and that read was
  // accurate when it was taken — so a repository whose only missing labels
  // were these two still shows the box, and it says so instead of naming
  // none.
  'labels:missing': (r) => {
    const created = PLAN_ISSUE_LABELS.map((label) => label.name);
    const missing = SEEDED_LABELS.filter((name) => !r.labels.includes(name) && !created.includes(name));
    return missing.length === 0
      ? `nothing left here: the only labels missing were \`${created.join('`, `')}\`, and opening this issue created both`
      : `create the ${missing.length} missing label(s) of the loop's vocabulary (\`${missing.join('`, `')}\`)`;
  },
  'hooks:not-installed': () =>
    `install the \`pre-push\` hook that keeps commits off the default branch (\`node scripts/init.mts\`)`,
  'workflows:missing': (r) => {
    const missing = OWNED_WORKFLOWS.filter((name) => !r.workflows.includes(name));
    return `copy the missing workflow(s) (\`${missing.join('`, `')}\`) into \`.github/workflows\``;
  },
  'test-command:none': () =>
    'set `AGENTIC_TEST_CMD`, or add a test command detection can find — `negative-control` proves nothing without one',
  'record:stale': (r) =>
    `regenerate \`${RECORD_FILE}\` (\`node scripts/adopt.mts --record --force\`): detection no longer agrees with it on ` +
    `\`${(r.record?.stale ?? []).join('`, `')}\`, and detection is what the loop follows`,
};

function renderPlan(report: Report): string {
  const ruleset =
    report.ruleset === null
      ? 'absent'
      : `\`${report.ruleset.rules.join('`, `')}\` — ${report.ruleset.requiredApprovingReviewCount} approving review(s) required`;
  const labelsPresent = SEEDED_LABELS.filter((name) => report.labels.includes(name)).length;
  // The checklist below says which labels are missing, and that list is drawn
  // from one page of `gh label list`. When the page came back full, it is a
  // guess — so the person ticking the box is told before they tick it.
  const labelsNote = report.labelsTruncated
    ? ` — **the label read returned its full page of ${LABEL_LIST_LIMIT} and may be truncated**, so a label listed as missing below may be one this read never saw`
    : '';
  const workflowsPresent = OWNED_WORKFLOWS.filter((name) => report.workflows.includes(name)).length;
  const has = [
    `- Stack: \`${report.stack}\` (${report.source})`,
    `- Test command: ${show(report.test)}`,
    `- Check command: ${show(report.check)}`,
    `- Default branch: \`${report.defaultBranch}\``,
    `- Ruleset on \`${report.defaultBranch}\`: ${ruleset}`,
    `- Labels: ${labelsPresent}/${SEEDED_LABELS.length} of the loop's vocabulary present${labelsNote}`,
    `- Hooks: ${report.hooks.length === 0 ? 'none installed' : `\`${report.hooks.join('`, `')}\``}`,
    `- Workflows: ${workflowsPresent}/${OWNED_WORKFLOWS.length} of the loop's workflows present`,
    `- Auto-merge: ${report.autoMerge ? 'enabled' : 'disabled'}`,
    `- Delete branch on merge: ${report.deleteBranchOnMerge ? 'enabled' : 'disabled'}`,
    `- Adoption record: ${
      report.record === null
        ? 'none'
        : `generated by ${codeSpan(report.record.generatedBy)} at ${codeSpan(report.record.generatedAt)}${
            report.record.stale.length === 0 ? '' : `, stale on \`${report.record.stale.join('`, `')}\``
          }`
    }`,
  ].join('\n');
  const plan =
    report.gaps.length === 0
      ? 'Nothing: this repository already has everything the loop reads.'
      : report.gaps.map((gap) => `- [ ] \`${gap}\` — ${REMEDIES[gap](report)}`).join('\n');
  return [
    'The agent loop reads a repository, it does not assume one. This is what it reads here today;',
    'nothing has been changed to produce it (`node scripts/adopt.mts --inventory`).',
    '',
    '## What this repository has',
    '',
    has,
    '',
    '## What adoption would do',
    '',
    plan,
    '',
    'Tick what should happen, then move this issue to `human:decided`.',
    '',
    // The globs adoption may write, declared here because this is the issue
    // the adoption pull request closes and `ci/scope-check.mts` reads a pull
    // request's scope off the issue, never off the body the opener wrote
    // (#155). Fixed rather than derived from the report above: the record
    // that decides the exact paths does not exist yet when this is rendered.
    '## Files',
    '',
    ADOPTION_GLOBS.map((glob) => `- \`${glob}\``).join('\n'),
    '',
    '## Inventory',
    '',
    '```json',
    JSON.stringify(report, null, 2),
    '```',
  ].join('\n');
}

// --- 8. --plan-issue: refuse when one is already open -----------------------
// The labels are read too, so the two states an open plan issue can be in are
// two answers rather than one (#302). An issue still carrying `human:pending`
// is a question nobody has answered: read it. One carrying `human:decided` is
// a question that *was* answered, and asking it again would put a second
// decision beside the standing one and make `--pr` ambiguous; the next step
// there is `--pr`, not another issue.
const search = gh(['issue', 'list', '--search', `"${PLAN_ISSUE_TITLE}" in:title`, '--state', 'open', '--json', 'number,title,labels']);
if (search.status !== 0 || !search.stdout.trim()) fail('plan-issue:unreadable');
type OpenIssue = { number?: number; title?: string; labels?: Array<{ name?: string } | string> };
let open: OpenIssue[];
try {
  open = JSON.parse(search.stdout);
} catch {
  fail('plan-issue:unreadable');
}
if (!Array.isArray(open)) fail('plan-issue:unreadable');
const already = open.find((issue) => issue?.title === PLAN_ISSUE_TITLE);
if (already) {
  const labels = (already.labels ?? []).map((label) => (typeof label === 'string' ? label : (label?.name ?? '')));
  const decided = labels.includes(DECIDED_LABEL);
  console.log(
    JSON.stringify({
      refused: decided
        ? `the adoption plan issue (#${already.number}) already carries \`${DECIDED_LABEL}\`: the question has been answered, and a second ` +
          'issue would put a second decision beside the standing one. Run `node scripts/adopt.mts --pr` to act on it.'
        : `an adoption plan issue is already open (#${already.number}); read it, or close it and run again.`,
      reason: decided ? 'plan-issue:already-decided' : 'plan-issue:already-open',
      issue: already.number ?? null,
    }),
  );
  process.exit(1);
}

// --- 9. --plan-issue: the labels, then the issue -----------------------------
// `human:pending` has to exist before the issue can carry it, and
// `human:decided` before the issue's last line can ask for it; the inventory
// already says whether either does, so this costs no extra read. Both are
// written before the issue, so a person who opens the plan has nothing to
// create — that is the whole of #366.
//
// The guard, not `--force`, is what leaves a label alone: a label the
// inventory read saw is never passed to `gh label create` at all, so a colour
// or a description a person chose stays theirs. `--force` acts only in the
// window that read missed — `labelsTruncated`, where the label exists off the
// page, or a label created between the read and this write — and there it
// does rewrite colour and description to the values above. It stays, because
// without it that window ends the run with `label:<name>:not-created` over a
// label that exists, and telling "already exists" apart from a real failure
// would mean reading `gh`'s wording, which `fail` above exists to avoid.
for (const label of PLAN_ISSUE_LABELS) {
  if (inventory.labels.includes(label.name)) continue;
  const write = gh(['label', 'create', label.name, '--color', label.color, '--description', label.description, '--force']);
  if (write.status !== 0) fail(`label:${label.name}:not-created`);
}

const created = gh(['issue', 'create', '--title', PLAN_ISSUE_TITLE, '--label', PENDING_LABEL, '--body', renderPlan(report)]);
if (created.status !== 0) fail('plan-issue:not-created', (created.stderr || created.stdout || '').trim().split('\n')[0] || undefined);
const url = created.stdout.trim().split('\n').filter(Boolean).pop() ?? '';
const number = Number(url.match(/\/(\d+)\s*$/)?.[1]);
if (!Number.isInteger(number)) fail('plan-issue:unreadable');
// `report.gaps`, not `inventory.gaps`: the body above was rendered from the
// report, so printing the inventory's list would leave the one gap the
// record introduces in the issue and out of the JSON a caller reads.
console.log(JSON.stringify({ issue: number, url, gaps: report.gaps }));
