#!/usr/bin/env node
// adopt — reports what a repository has, and asks before writing anything
// (#162). `scripts/init.mts` writes first and reports afterwards, which is
// the wrong order for a repository that is not yours; this script reverses
// it. Run from inside the repository being looked at.
//
//   node scripts/adopt.mts --inventory
//   node scripts/adopt.mts --plan-issue
//   node scripts/adopt.mts --record [--force]
//   node scripts/adopt.mts --workflows
//
// `--inventory` prints the report of `scripts/lib/adopt/inventory.mts` as
// JSON on stdout and performs **no write of any kind**: no file is created
// or touched, and the only `gh` calls are reads (`api repos/{owner}/{repo}`,
// the default branch's effective rules, `label list`). It reads one more
// thing from disk than the inventory does — the adoption record, below.
//
// `--plan-issue` is the one mutation, and it is a question rather than a
// change: it opens a single `human:pending` issue whose body renders the
// inventory and lists, as checkboxes, exactly the gaps found and what
// adoption would do about each. The pattern is this repository's own —
// `.github/workflows/guard-main.yml` opens exactly such an issue,
// deduplicated by title — and the three readers that honour the label
// (`scripts/reconcile.mts`, `scripts/claim.mts` and the Codex route's
// `github.mts`) are already in place. A second run never opens a second
// issue: it refuses with `{ refused, reason: 'plan-issue:already-open' }`.
// A repository whose report names no gap gets no issue either: there is no
// question to ask, and it refuses with
// `{ refused, reason: 'plan-issue:nothing-to-plan', gaps: [] }` before it
// searches for an open one, so that run makes no `gh` call beyond the
// inventory's own reads.
//
// `--record` is the second mutation, and it writes exactly one file:
// `agentic.config.json` at the repository root, the adoption record of
// `docs/decisions.md` item 15, built from the inventory by
// `scripts/lib/adopt/record.mts` — the one writer. It refuses to overwrite a
// record whose `generatedBy` is not this tool (`record:not-ours`); `--force`
// is the way past that refusal. Either way a rewrite reports every field
// that changed.
//
// **Detection stays the default.** The record is compared with what
// `ci/lib/detect.mts` says on *every* run, not only when it is written, and
// `--inventory` reports each field where the two disagree as the gap
// `record:stale`. That comparison lives here rather than in
// `inventory.mts` because the inventory is what a repository *has*, read
// once; the record is a layer over it, and the values to compare against —
// `stack`, `test`, `check` — are already in the report, so no second
// detection run happens.
//
// `--workflows` is the third mutation, and it writes only under the adopted
// repository's `.github/workflows/`: the three files
// `scripts/lib/adopt/workflows.mts` renders from the record (#165), which also
// returns the list of check names those files produce — one list for the
// workflow and for the ruleset, so the two cannot name different checks. The
// record is the input and is required: without one it refuses with
// `{ refused, reason: 'workflows:no-record' }` rather than detecting a second
// time. A file that does not carry the `generated by agentic-setup adopt`
// marker on its first lines was written by a person and is reported as
// `skipped` — there is no `--force` past that, because the remedy is to read
// the file, not to lose it. A file that is already what would be written is
// `skipped` too, and nothing is rewritten.
//
// **Crash policy: fail closed.** Any `git` or `gh` read that cannot answer
// prints `{ error: <named reason> }` and exits 1. No field is ever reported
// as absent because the read for it failed — "there is no ruleset" and "the
// ruleset could not be read" are different answers, and a caller acting on
// the first when the second is true would delete a protection it never saw.
// The record is held to the same rule on every flag, `--inventory`
// included: a record that is not the shape prints `{ error, field }` and
// exits 1 rather than being ignored, because a rejected record silently read
// as "no record" is a stale configuration nothing would ever report. A usage
// problem is reported the same way, before any call is made.
//
// Node built-ins only.
import { spawnSync } from 'node:child_process';
import { parseArgs } from '../ci/lib/args.mts';
import {
  LABEL_LIST_LIMIT,
  OWNED_WORKFLOWS,
  SEEDED_LABELS,
  isFailure,
  takeInventory,
  type CommandResult,
  type Gap,
  type Inventory,
} from './lib/adopt/inventory.mts';
import {
  GENERATED_BY,
  RECORD_FILE,
  RecordError,
  buildRecord,
  diffRecords,
  readRecord,
  staleFields,
  writeRecord,
  type AdoptionRecord,
} from './lib/adopt/record.mts';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
  WORKFLOW_DIR,
  WorkflowError,
  isGenerated,
  readTemplates,
  renderWorkflows,
} from './lib/adopt/workflows.mts';

const USAGE = 'usage: node scripts/adopt.mts --inventory | --plan-issue | --record [--force] | --workflows';

/** The title the plan issue is deduplicated by; one per repository. */
const PLAN_ISSUE_TITLE = 'Adoption plan: what this repository is missing';

/** The label the plan issue carries, with the colour scripts/init.mts seeds. */
const PENDING_LABEL = 'human:pending';
const PENDING_COLOR = 'f9d0c4';
const PENDING_DESCRIPTION = 'A human decision is required; affected work is paused';

/**
 * The one way out on a failure: a *named* reason in `error`, so a caller can
 * branch on it, with the underlying tool's own message in `detail` when
 * there is one. gh's wording is not a contract and must never be the name.
 */
function fail(reason: string, detail?: string): never {
  console.log(JSON.stringify(detail ? { error: reason, detail } : { error: reason }));
  process.exit(1);
}

/** The same exit for a record this tool refuses, with the field it rejected. */
function failRecord(err: RecordError): never {
  const field = err.field === null ? {} : { field: err.field };
  console.log(JSON.stringify({ error: err.reason, ...field, detail: err.message }));
  process.exit(1);
}

function gh(args: string[]): CommandResult {
  const r = spawnSync('gh', args, { encoding: 'utf8' });
  return { status: r.status ?? 1, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
}

/** `git` inside the repository being described; `cwd` is bound in step 2. */
function gitIn(cwd: string) {
  return (args: string[]): CommandResult => {
    const r = spawnSync('git', args, { cwd, encoding: 'utf8' });
    return { status: r.status ?? 1, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
  };
}

// --- 1. the flags, before anything is read ----------------------------------
const flags = parseArgs(process.argv.slice(2));
const wantInventory = flags.inventory === true;
const wantPlanIssue = flags['plan-issue'] === true;
const wantRecord = flags.record === true;
const wantWorkflows = flags.workflows === true;
const force = flags.force === true;
// Exactly one mode. `--force` is a modifier of `--record` and never a mode
// of its own: on its own it names nothing to do, and it must not be read as
// "write the record" by accident.
if ([wantInventory, wantPlanIssue, wantRecord, wantWorkflows].filter(Boolean).length !== 1) fail(USAGE);
if (force && !wantRecord) fail(USAGE);

// --- 2. the repository root -------------------------------------------------
const top = spawnSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' });
if (top.status !== 0 || !(top.stdout ?? '').trim()) fail('root:not-a-git-repository');
const root = top.stdout.trim();

// --- 3. the report ----------------------------------------------------------
const inventory = takeInventory(root, gh, gitIn(root));
if (isFailure(inventory)) fail(inventory.error);

// --- 4. the adoption record, read on every run ------------------------------
// Read before anything is written, and validated before it is believed. A
// record that is not the shape stops the run here, whichever flag asked.
let existing: AdoptionRecord | null;
try {
  existing = readRecord(root);
} catch (err) {
  if (err instanceof RecordError) failRecord(err);
  throw err;
}

/** What the report says about the record: never the record itself, which detection replaces. */
type RecordView = { generatedBy: string; generatedAt: string; stale: string[] } | null;
type ReportGap = Gap | 'record:stale';
type Report = Omit<Inventory, 'gaps'> & { gaps: ReportGap[]; record: RecordView };

const stale = existing === null ? [] : staleFields(existing, inventory);
const record: RecordView =
  existing === null ? null : { generatedBy: existing.generatedBy, generatedAt: existing.generatedAt, stale };
const report: Report = {
  ...inventory,
  gaps: stale.length > 0 ? [...inventory.gaps, 'record:stale'] : inventory.gaps,
  record,
};

if (wantInventory) {
  console.log(JSON.stringify(report));
  process.exit(0);
}

// --- 4b. --workflows: the files the record generates -------------------------
// Placed here, between the report and `--record`, because it is a reader of
// the record rather than a producer of one: the record is its only input, and
// a repository without one is refused rather than detected a second time.
// Everything it writes goes under `<root>/.github/workflows/`; nothing else on
// disk is touched, and the marker is what keeps a hand-written file safe.
if (wantWorkflows) {
  if (existing === null) {
    console.log(
      JSON.stringify({
        refused:
          `there is no ${RECORD_FILE} to generate from; run \`node scripts/adopt.mts --record\` first. ` +
          'The workflows are rendered from the record, so that the checks they produce and the checks the ' +
          'ruleset requires are one list rather than two.',
        reason: 'workflows:no-record',
      }),
    );
    process.exit(1);
  }

  /** The same exit as `failRecord`, for a render this tool refuses. */
  const failWorkflow = (err: WorkflowError): never => {
    const field = err.field === null ? {} : { field: err.field };
    console.log(JSON.stringify({ error: err.reason, ...field, detail: err.message }));
    process.exit(1);
  };

  let rendering;
  try {
    rendering = renderWorkflows(existing, readTemplates());
  } catch (err) {
    if (err instanceof WorkflowError) failWorkflow(err);
    throw err;
  }

  /** What happened to one file, and why. `skipped` always carries its reason. */
  type Outcome = { file: string; outcome: 'created' | 'updated' | 'skipped'; reason: string; jobs: string[] };
  const outcomes: Outcome[] = [];

  for (const rendered of rendering.files) {
    const shown = `${WORKFLOW_DIR}/${rendered.name}`;
    const path = join(root, WORKFLOW_DIR, rendered.name);
    // Only ENOENT is "there is no such file"; every other errno fails closed,
    // because writing over a file that could not be read is exactly what the
    // marker exists to prevent.
    let current: string | null;
    try {
      current = readFileSync(path, 'utf8');
    } catch (err) {
      if ((err as NodeJS.ErrnoException)?.code !== 'ENOENT') fail('workflows:unreadable', (err as Error).message);
      current = null;
    }

    if (current !== null && !isGenerated(current)) {
      outcomes.push({ file: shown, outcome: 'skipped', reason: 'not-generated', jobs: rendered.jobs });
      continue;
    }
    if (current === rendered.content) {
      outcomes.push({ file: shown, outcome: 'skipped', reason: 'unchanged', jobs: rendered.jobs });
      continue;
    }
    try {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, rendered.content);
    } catch (err) {
      fail('workflows:not-written', (err as Error).message);
    }
    outcomes.push({
      file: shown,
      outcome: current === null ? 'created' : 'updated',
      reason: current === null ? 'absent' : 'regenerated',
      jobs: rendered.jobs,
    });
  }

  // `checks` is the list the renderer returned — the job names of the file it
  // rendered, not a second computation over what was written. `record.checks`
  // is what the default branch's ruleset requires today, as the inventory read
  // it, so the difference is the work the ruleset still needs.
  console.log(
    JSON.stringify({
      workflows: outcomes,
      checks: rendering.checks,
      missingFromRuleset: rendering.checks.filter((name) => !existing.checks.includes(name)),
      gaps: rendering.gaps,
    }),
  );
  process.exit(0);
}

// --- 5. --record: the one file adoption generates ---------------------------
if (wantRecord) {
  if (existing !== null && existing.generatedBy !== GENERATED_BY && !force) {
    console.log(
      JSON.stringify({
        refused:
          `${RECORD_FILE} says it was generated by \`${existing.generatedBy}\`, not by this tool; ` +
          'no person edits this file. Run `--record --force` to regenerate it, losing every hand edit.',
        reason: 'record:not-ours',
        generatedBy: existing.generatedBy,
      }),
    );
    process.exit(1);
  }
  const next = buildRecord(inventory);
  const changed = existing === null ? [] : diffRecords(existing, next);
  try {
    writeRecord(root, next);
  } catch (err) {
    fail('record:not-written', (err as Error).message);
  }
  console.log(JSON.stringify({ record: RECORD_FILE, written: true, changed }));
  process.exit(0);
}

// --- 6. --plan-issue: a repository with nothing to plan is not asked --------
// The plan issue is a question ("should adoption do these things?"), and a
// repository whose report names no gap has none to answer: the issue would
// carry an empty checklist, and a person would have to open it to find that
// out. `report.gaps`, not `inventory.gaps` — a stale record is worth
// planning even when the repository itself is whole. Refused here, before
// the open-issue search and before the label, so this run makes no `gh`
// call at all beyond the reads the inventory already did.
if (report.gaps.length === 0) {
  console.log(
    JSON.stringify({
      refused:
        'this repository already has everything the loop reads; there is nothing to plan, and an issue with an ' +
        'empty checklist asks nothing. Run `--inventory` to see the report it was decided from.',
      reason: 'plan-issue:nothing-to-plan',
      gaps: [],
    }),
  );
  process.exit(1);
}

// --- 7. --plan-issue: render the plan ---------------------------------------
const show = (value: string | null): string => (value === null ? 'none' : `\`${value}\``);

/** What adoption would do about each gap, in the gap's own words. */
const REMEDIES: Record<ReportGap, (report: Report) => string> = {
  'ruleset:absent': (r) =>
    `create the \`agentic-setup\` branch ruleset on \`${r.defaultBranch}\` (\`node scripts/init.mts --rules\`), ` +
    'requiring a pull request and the checks the merge gate reads',
  'ruleset:review-not-required': () =>
    "raise the ruleset's `required_approving_review_count` to 1, so an approval is what merges a pull request " +
    'rather than a label anyone can apply',
  'labels:missing': (r) => {
    const missing = SEEDED_LABELS.filter((name) => !r.labels.includes(name));
    return `create the ${missing.length} missing label(s) of the loop's vocabulary (\`${missing.join('`, `')}\`)`;
  },
  'hooks:not-installed': () =>
    `install the \`pre-push\` hook that keeps commits off the default branch (\`node scripts/init.mts\`)`,
  'workflows:missing': (r) => {
    const missing = OWNED_WORKFLOWS.filter((name) => !r.workflows.includes(name));
    return `copy the missing workflow(s) (\`${missing.join('`, `')}\`) into \`.github/workflows\``;
  },
  'test-command:none': () =>
    'set `AGENTIC_TEST_CMD`, or add a test command detection can find — `negative-control` proves nothing without one',
  'record:stale': (r) =>
    `regenerate \`${RECORD_FILE}\` (\`node scripts/adopt.mts --record --force\`): detection no longer agrees with it on ` +
    `\`${(r.record?.stale ?? []).join('`, `')}\`, and detection is what the loop follows`,
};

function renderPlan(report: Report): string {
  const ruleset =
    report.ruleset === null
      ? 'absent'
      : `\`${report.ruleset.rules.join('`, `')}\` — ${report.ruleset.requiredApprovingReviewCount} approving review(s) required`;
  const labelsPresent = SEEDED_LABELS.filter((name) => report.labels.includes(name)).length;
  // The checklist below says which labels are missing, and that list is drawn
  // from one page of `gh label list`. When the page came back full, it is a
  // guess — so the person ticking the box is told before they tick it.
  const labelsNote = report.labelsTruncated
    ? ` — **the label read returned its full page of ${LABEL_LIST_LIMIT} and may be truncated**, so a label listed as missing below may be one this read never saw`
    : '';
  const workflowsPresent = OWNED_WORKFLOWS.filter((name) => report.workflows.includes(name)).length;
  const has = [
    `- Stack: \`${report.stack}\` (${report.source})`,
    `- Test command: ${show(report.test)}`,
    `- Check command: ${show(report.check)}`,
    `- Default branch: \`${report.defaultBranch}\``,
    `- Ruleset on \`${report.defaultBranch}\`: ${ruleset}`,
    `- Labels: ${labelsPresent}/${SEEDED_LABELS.length} of the loop's vocabulary present${labelsNote}`,
    `- Hooks: ${report.hooks.length === 0 ? 'none installed' : `\`${report.hooks.join('`, `')}\``}`,
    `- Workflows: ${workflowsPresent}/${OWNED_WORKFLOWS.length} of the loop's workflows present`,
    `- Auto-merge: ${report.autoMerge ? 'enabled' : 'disabled'}`,
    `- Delete branch on merge: ${report.deleteBranchOnMerge ? 'enabled' : 'disabled'}`,
    `- Adoption record: ${
      report.record === null
        ? 'none'
        : `generated by \`${report.record.generatedBy}\` at ${report.record.generatedAt}${
            report.record.stale.length === 0 ? '' : `, stale on \`${report.record.stale.join('`, `')}\``
          }`
    }`,
  ].join('\n');
  const plan =
    report.gaps.length === 0
      ? 'Nothing: this repository already has everything the loop reads.'
      : report.gaps.map((gap) => `- [ ] \`${gap}\` — ${REMEDIES[gap](report)}`).join('\n');
  return [
    'The agent loop reads a repository, it does not assume one. This is what it reads here today;',
    'nothing has been changed to produce it (`node scripts/adopt.mts --inventory`).',
    '',
    '## What this repository has',
    '',
    has,
    '',
    '## What adoption would do',
    '',
    plan,
    '',
    'Tick what should happen, then move this issue to `human:decided`.',
    '',
    '## Inventory',
    '',
    '```json',
    JSON.stringify(report, null, 2),
    '```',
  ].join('\n');
}

// --- 8. --plan-issue: refuse when one is already open -----------------------
const search = gh(['issue', 'list', '--search', `"${PLAN_ISSUE_TITLE}" in:title`, '--state', 'open', '--json', 'number,title']);
if (search.status !== 0 || !search.stdout.trim()) fail('plan-issue:unreadable');
let open: Array<{ number?: number; title?: string }>;
try {
  open = JSON.parse(search.stdout);
} catch {
  fail('plan-issue:unreadable');
}
if (!Array.isArray(open)) fail('plan-issue:unreadable');
const already = open.find((issue) => issue?.title === PLAN_ISSUE_TITLE);
if (already) {
  console.log(
    JSON.stringify({
      refused: `an adoption plan issue is already open (#${already.number}); read it, or close it and run again.`,
      reason: 'plan-issue:already-open',
      issue: already.number ?? null,
    }),
  );
  process.exit(1);
}

// --- 9. --plan-issue: the one mutation --------------------------------------
// The label has to exist before it can be applied; the inventory already
// says whether it does, so this costs no extra read.
if (!inventory.labels.includes(PENDING_LABEL)) {
  const label = gh(['label', 'create', PENDING_LABEL, '--color', PENDING_COLOR, '--description', PENDING_DESCRIPTION, '--force']);
  if (label.status !== 0) fail(`label:${PENDING_LABEL}:not-created`);
}

const created = gh(['issue', 'create', '--title', PLAN_ISSUE_TITLE, '--label', PENDING_LABEL, '--body', renderPlan(report)]);
if (created.status !== 0) fail('plan-issue:not-created', (created.stderr || created.stdout || '').trim().split('\n')[0] || undefined);
const url = created.stdout.trim().split('\n').filter(Boolean).pop() ?? '';
const number = Number(url.match(/\/(\d+)\s*$/)?.[1]);
if (!Number.isInteger(number)) fail('plan-issue:unreadable');
// `report.gaps`, not `inventory.gaps`: the body above was rendered from the
// report, so printing the inventory's list would leave the one gap the
// record introduces in the issue and out of the JSON a caller reads.
console.log(JSON.stringify({ issue: number, url, gaps: report.gaps }));
